services:
  - type: web
    name: absurd-zoo-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: EVENT_CHANNEL
        sync: false
    plan: free
